version: '3.8'

services:
  # Serviço do app Laravel
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    environment:
      - "DB_HOST=db"
      - "REDIS_HOST=cache"
    depends_on:
      - db
      - cache

  # Serviço Nginx
  webserver:
    image: nginx:alpine
    container_name: nginx_webserver
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - nginx_logs:/var/log/nginx
    depends_on:
      - app

  # Serviço MySQL
  db:
    image: mysql:5.7
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: loja_api
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: lojauser
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql

  # Serviço Redis
  cache:
    image: redis:alpine
    container_name: redis_cache
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data:
  nginx_logs:
